name: Woodcutter
version: '${version}'
main: woodcutter.wc.Main
api-version: 1.18
authors: [Seaoftrees08]
description: for Wood Cutter

commands:
  woodcutter:
    aliases: wct
    description: This is WoodCutterPlugin's command.
    usage: /woodcutter
    permission: woodcutter.woodcutter
permissions:
  woodcutter.woodcutter:
    description: woodcutterCommandPermission
    default: true
